### ISSUE TITLE
TypeError: rule(...) is not a function

### ISSUE THREAD

**Issue by mik01aj** [rstacruz/stylelint-rscss#3] opened 2016-09-20 12:51 UTC
This is my `stylelint` config:

```
{
    "plugins": [
        "stylelint-rscss"
    ],
    "rules": {
        "rscss/no-descendant-combinator": false,
    }
}
```

Yes, that's right, I removed everything except this one rule.
When running stylelint, I get this:

```
TypeError: rule(...) is not a function
    at /...../node_modules/stylelint/dist/postcssPlugin.js:124:46
    at Array.forEach (native)
    at /...../node_modules/stylelint/dist/postcssPlugin.js:103:33
```

Needless to say, with other rules it works fine. Using `stylelint@7.2.0` and `stylelint-rscss@0.3.1`.

**Comment by rstacruz** [comment] 2016-09-20 13:51
What was the input?

**Comment by mik01aj** [comment] 2016-09-20 13:55
Lots of scss files. It's hard to tell which triggered the error. If needed, I can check later.

This is the line in `stylelint/dist/postcssPlugin.js` that throws the exception:
![image](https://cloud.githubusercontent.com/assets/3027415/18673001/8747adea-7f4a-11e6-8dcb-4bdcdb133475.png)

Looks like the highlighted part returned something that is not a function.

**Comment by rstacruz** [comment] 2016-09-21 06:51
honestly no clue, it looks like the plugin failed to load. it works for me (tm) and I can't seem to reproduce it with stylelint-rscss@0.3.1.

**Comment by rstacruz** [comment] 2016-09-21 06:51
ah, right, `false` will trigger it

**Comment by rstacruz** [comment] 2016-09-21 06:56
Fixed in 0.3.2 :)

**Closed as completed by rstacruz** 2016-09-21 06:56 UTC

**Comment by mik01aj** [comment] 2016-09-21 08:09
well, maybe it should be `null`. But you had `false` in the recommended config.

**Comment by rstacruz** [comment] 2016-09-21 11:04
Ah, absolutely. Null will work too by the way; it only does its thing if
it's truthy.
